### ISSUE TITLE
Not registering input

### ISSUE THREAD

**Issue by VNRARA** [FabianHenneke/WearAuthn#4] opened 2020-03-04 02:52 UTC
The top connect button (with my bluetooth device name) doesn't work when already connected to a phone. It doesn't give an error msg or force connecting to a different device.

**Comment by FabianHenneke** [comment] 2020-03-04 13:03
Could you maybe take a screenshot or photo of the situation in which you can't connect? This will help me get to the bottom of this.
WearAuthn unfortunately can't be used with phones via Bluetooth, so it shouldn't connect to one in the first place.

**Comment by VNRARA** [comment] 2020-03-07 05:38
I mean when it's connected to my phone to accept phone calls it hangs up the Bluetooth connection so I can't use the app to connect to a laptop. I have to disable Bluetooth on the watch and re-enable for it to work;.

**Comment by FabianHenneke** [comment] 2020-03-07 13:50
I see, I think I understand the problem now. Could you tell me which watch model you are using (Settings ->System -> About) and which version of Android you have installed (Settings ->System -> About -> Versions)?

Ideally, you would try whether you can reproduce the same issue with the app [WearMouse](https://play.google.com/store/apps/details?id=com.ginkage.wearmouse), which shares most of the underlying Bluetooth stack with WearAuthn. If you can reproduce the issue there, it is extremely likely that this is a problem with Wear OS itself and therefore can't be fixed.

**Comment by VNRARA** [comment] 2020-03-18 23:28
TicWatch Pro (WF12096) on WearOS 2.14 H. Wearmouse isn't having this issue. But it seems to be using the system ui to prompt and dialog for connecting a device Bluetooth ? Haven't really payed much attention to the issue, tho.

**Comment by FabianHenneke** [comment] 2020-03-24 14:35
WearMouse only does a very good job at mimicking the system UI, but doesn't use it. 

Does the problem always manifest itself with WearAuthn after you have taken a phone call on the watch? And it does not appear with WearMouse? 

I will look into the difference between the two apps and let you know when I find anything.

**Comment by VNRARA** [comment] 2020-03-30 23:40
It seems not to do it. But I haven't really used it that much anymore. Google's IP based SSO is only for business/suite owners and risking a password hack because of convenience isn't worth it. So as my second layer of auth I usually use the Google Prompt.

**Comment by VNRARA** [comment] 2020-03-31 06:35
It stopped attaching altogether... It says attaching but it never does.

**Comment by FabianHenneke** [comment] 2020-04-14 10:18
Sorry for the late reply, but I have unfortunately been unable to make any progress on tracking down this bug. 

> It stopped attaching altogether... It says attaching but it never does. I reset my bluetooth device on my pc and reset my watch and it works like before.

This sometimes happens when switching between different apps emulating a HID device (such as WearMouse and WearAuthn) and can usually be resolved by repairing with the target device. Unfortunately, this also seems to be an inherent limitation of the Wear OS bluetooth stack.

**Comment by FabianHenneke** [comment] 2020-04-19 09:27
I have made some changes to the Bluetooth backend that may resolve this issue. If this should not resolve the issue for you, please reopen.

**Closed by FabianHenneke** 2020-04-19 09:27 UTC
Labels: bug

**Comment by VNRARA** [comment] 2020-06-21 22:55
I found out that it may be related to some Wear devices being able to connect as headset and disabling the "Play phone audio on watch" and turning my Phone bluetooth made it connect instantly today after a while of reconnecting and removing device from Windows Bluetooth devices.

**Comment by FabianHenneke** [comment] 2020-06-22 09:21
It's quite possible that Windows does not like to see HID devices that double as headsets, so this might very well have been the issue. Thanks for the info!

**Comment by VNRARA** [comment] 2022-05-12 02:11
I found out with my new watch that the watches don't like being connected via BLE (to the phone) and at the same time do WearAuthn stuff. 

> Windows does not like to see HID devices that double as headsets

Is there any other OS/devices that uses bluetooth with wearAuthn besides Windows? Should this work with linux?

**Comment by VNRARA** [comment] 2023-08-12 20:41
I think the problem might have been #22 all along
